version: '3.1'
services:
#  web_server:
#    build:
#      context: .
#    environment:
#      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
#      - EXTERNAL_PORT=${EXTERNAL_PORT}
#      - APP_PORT=${APP_PORT}
#    ports:
#      - "${EXTERNAL_PORT}:${APP_PORT}"
#    env_file:
#      - ".env"
  mongo:
    image: mongo
    volumes:
      - /var/lib/mongodb/jsb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ".env"