version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - /var/lib/mongodb/jsb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ".env"