"""
Константы для сценария бота.
"""
(MAIN_MENU, ADMIN, REGISTER_STATION, REGISTER_STATION_WITH_DIRECTION,
 REGISTERED_STATIONS, REGISTERED_STATIONS_WITH_DIRECTION, DEPARTURE_STATION, ARRIVED_STATION,
 EDIT_STATION, SCHEDULE_VIEW) = range(10)
