"""
Константы для сценария бота.
"""
(MAIN_MENU, ADMIN, REGISTER_STATION, REGISTER_STATION_FROM_MOSCOW, REGISTER_STATION_TO_MOSCOW,
 REGISTERED_STATIONS, REGISTERED_STATIONS_FROM_MOSCOW, REGISTERED_STATIONS_TO_MOSCOW, SCHEDULE,
 DEPARTURE_STATION) = range(10)
