"""
Константы для сценария бота.
"""
(MAIN_MENU, ADMIN, REGISTER_STATION, REGISTER_STATION_WITH_DIRECTION,
 REGISTERED_STATIONS, REGISTERED_STATIONS_WITH_DIRECTION, SCHEDULE, DEPARTURE_STATION, EDIT_STATION) = range(9)
